- name: Ansible Automation Platform
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update RHEL-based systems
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
        update_only: true

    - name: Register subscription for RHEL
      when: ansible_os_family == 'RedHat'
      community.general.redhat_subscription:
        username: "{{ lookup('env', 'RHN_USERNAME') }}"
        password: "{{ lookup('env', 'RHN_PASSWORD') }}"

    - name: Enable repository management for RHEL
      when: ansible_os_family == 'RedHat'
      ansible.builtin.command:
        cmd: subscription-manager config --rhsm.manage_repos=1
    - name: Install Ansible Automation Platform installer package for RHEL {{ ansible_distribution_major_version }}
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        enablerepo: ansible-automation-platform-2.4-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms
        name: ansible-automation-platform-installer
        state: present
