---
name: Packer build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
  RHN_USERNAME: ${{ vars.RHN_USERNAME }}
  RHN_PASSWORD: ${{ secrets.RHN_PASSWORD }}
  HCP_CLIENT_ID: ${{ vars.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ vars.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ vars.HCP_ORGANIZATION_ID }}
  HCP_BUCKET_NAME: ${{ vars.HCP_BUCKET_NAME }}


jobs:
  packer_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: AWS Get Caller Identity
        run: aws sts get-caller-identity

      - name: Packer Init
        run: packer init .

      - name: Packer Format
        run: packer fmt -check .

      - name: Packer Validate
        run: packer validate .

      - name: Packer Build
        run: packer build .